### ISSUE TITLE
add these DNS records to factoryx.org to validate emails

### ISSUE THREAD

**Issue by thowar2** [FACTORYX/x#2]
@funkytek 

DNS Host name (TXT record name): `google._domainkey`
TXT record value: `v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCnaJXA54+c5EMBVLmoZdSz+afMjf/jw/qF/OHwA48pVX0C3xXdD7ZZ/4Z1MsdRUJyk0Exm2N4gk4NuZ9BuF9agHKg5+Reb3vNhR22PjRbxsmG+claybO3mA3zd3pdN36X2ns3m1x+nz0NzAHTio7n0M2meIll0egK5v+dSfh9l7wIDAQAB`

Host: `@`
TXT Record value: `v=spf1 include:_spf.google.com ~all`

Host: `@`
TXT Record value: `google-site-verification=cRzA6x1HHxSoi_78j5QP604xc0ykU_S0xY6Z9SVSJpw`

**Comment by stephenlacy** [comment]
@thowar2 this is a public repo

**Comment by thowar2** [comment]
Woops, I'll get a new DKIM then.

**Comment by thowar2** [comment]
New DKIM sent to @funkytek via slack
